// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm-Voe0q3_a62V2XAE_4hbw-LsqLooyJs',
    appId: '1:146251124501:web:fdd9f37341bd6bfaaca31c',
    messagingSenderId: '146251124501',
    projectId: 'realchat-4202f',
    authDomain: 'realchat-4202f.firebaseapp.com',
    storageBucket: 'realchat-4202f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi8tnc8u-EoqOJFK6E41ngcJfCY9sDyM8',
    appId: '1:146251124501:android:6328d51de2606054aca31c',
    messagingSenderId: '146251124501',
    projectId: 'realchat-4202f',
    storageBucket: 'realchat-4202f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqRLVNYax48af61e6j3nyGn474BzlsNb8',
    appId: '1:146251124501:ios:6a9d15956be49a44aca31c',
    messagingSenderId: '146251124501',
    projectId: 'realchat-4202f',
    storageBucket: 'realchat-4202f.appspot.com',
    iosClientId: '146251124501-07jgn0fhc60t14gs2lv49f69dlf2u3rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.realchatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqRLVNYax48af61e6j3nyGn474BzlsNb8',
    appId: '1:146251124501:ios:6a9d15956be49a44aca31c',
    messagingSenderId: '146251124501',
    projectId: 'realchat-4202f',
    storageBucket: 'realchat-4202f.appspot.com',
    iosClientId: '146251124501-07jgn0fhc60t14gs2lv49f69dlf2u3rb.apps.googleusercontent.com',
    iosBundleId: 'com.example.realchatapp',
  );
}
